name: device_calendar_sandbox
description: A Sample Calendar App using Cubit.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_calendar: ^3.1.0
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  equatable: ^1.2.5
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/calendar_icon.png